export const clubs = ["Innovation", "Coding and Engineering Design", "Quiz and Mathematical Aptitude", "Gaming", "Robotics"];

export const events = [
  {
    "id": "0",
    "name": "",
    "club": "",
    "participation": "",
    "imgName": "",
    "poster": "",
    "about": "",
    "structure": "",
    "prizes": "",
    "timeline": "",
    "payment": 999,
    "contacts":
      [
        {
          "name": "",
          "number": "",
          "email": "",
        },
        {
          "name": "",
          "number": "",
          "email": "",
        },
        {
          "name": "",
          "number": "",
          "email": "",
        },
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "1",
    "name": "Innovative Idea Contest",
    "club": "Innovation",
    "participation": "Team Participation",
    "imgName": "./images/events/astronomy/astrohunt/image.jpg",
    "poster": "/images/events/astronomy/astrohunt/poster.jpg",
    "about": "Astro-Hunt is an astronomy-themed treasure hunt where you will come across mind boggling riddles, and to get closer to the finishing line, you will have to be faster than your competitors both in solving the riddles and in terms of reaching the next location.",
    "structure": "An exciting hunt with a pinch of Astronomy!",
    "prizes": "Prize Pool of 20,000/-",
    "timeline": "09:00 AM to 13:00 PM on January 28th, 2023",
    "payment": 199,
    "contacts":
      [
        {
          "name": "Shubhankar Bhatt",
          "number": "+91 9997078807",
          "email": "20UEC129@lnmiit.ac.in",
        },
        {
          "name": "Radhika Agarwal",
          "number": "+91 74518 47047",
          "email": "20UCC083@lnmiit.ac.in",
        },
        {
          "name": "Vaibhav Khamesra",
          "number": "+91 70236 59757",
          "email": "21UCS224@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/17Rmi03aB5-fmxWbvhjAJapWq6K10gYme/view?usp=share_link",
    "link": "",
    "clubemail": "astronomyclub@lnmiit.ac.in",
  },
  {
    "id": "2",
    "name": "Innovative Model Competition",
    "club": "Innovation",
    "participation": "Solo Participation",
    "imgName": "./images/events/astronomy/astromemia/image.jpg",
    "poster": "/images/events/astronomy/astromemia/poster.jpg",
    "about": "An online meme-making contest where you can use your understanding of astronomy and humour to make a meme that gets everyone in the room smiling. And anyway, what could be better than laughing while also winning something?",
    "structure": "Online Meme-Making competition themed on Astronomy.",
    "prizes": "Prizes Worth 10K!",
    "timeline": "13 January 2023 - Contest Starts 20 January 2023 - Submissions Close",
    "payment": 199,
    "contacts":
      [
        {
          "name": "Aman Aggawral",
          "number": "+91 73001 76925",
          "email": "20UME006@lnmiit.ac.in",
        },
        {
          "name": "Rudransh Sharma",
          "number": "+91 95991 35384",
          "email": "20UME043@lnmiit.ac.in",
        },
        {
          "name": "Ashwin Singh",
          "number": "+91 84128 11538",
          "email": "21UCC128@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/17PlRzH0VoFvmGduWgDuNh0u04yA9Lrjn/view?usp=share_link",
    "link": "",
    "clubemail": "astronomyclub@lnmiit.ac.in",
  },
  {
    "id": "3",
    "name": "Technical Poster Presentation",
    "club": "Innovation",
    "participation": "Team Participation",
    "imgName": "./images/events/astronomy/brahmaand/image.jpg",
    "poster": "/images/events/astronomy/brahmaand/poster.jpg",
    "about": "Brahmaand is an event where you present your frame of reference towards the problem statement and come with effective ways or solutions with the help of proven resources.",
    "structure": "Presentation making competition conducted in two rounds. Shortlisted candidates from the online round will be asked to present in offline mode in LNMIIT.",
    "prizes": "Prizes Worth 15K!",
    "timeline": "17:00 PM, 13 January 2023 - Problem statement will be released 23:59 PM, 15 January 2023 - Submission Deadline, 16:00 PM, 27 January 2023 - Shortlisted teams will get a chance to present their case studies to judges in offline mode",
    "payment": 199,
    "contacts":
      [
        {
          "name": "Aryan Aditya",
          "number": "+91 95999 77381",
          "email": "20UCS031@lnmiit.ac.in",
        },
        {
          "name": "Ayush Kumar Dhoot",
          "number": "+91 83687 14482",
          "email": "20UCS045@lnmiit.ac.in",
        },
        {
          "name": "Sai Ruthvik",
          "number": "+91 86882 74747",
          "email": "21UCS174@lnnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1kQxHnhn--ySWVMdAhFd2owXbL2xlC1Dt/view",
    "link": "https://unstop.com/competition/brahmaand-lnm-institute-of-information-technology-lnmiit-jaipur-584783",
    "clubemail": "astronomyclub@lnmiit.ac.in",
  },
  {
    "id": "4",
    "name": "Codefiesta",
    "club": "Coding and Engineering Design",
    "participation": "Solo Participation",
    "imgName": "./images/events/astronomy/dhoomketu/image.jpg",
    "poster": "/images/events/astronomy/dhoomketu/poster.jpg",
    "about": "Want to relax a little bit and take a break from the everyday hustle? The Astronomy club brings for you the Sky gazing session with many short and exciting events such as telescope handling, jamming sessions, poetry sessions, discussions on mythology, astrophysics and a lot more.",
    "structure": "A relaxing and entertaining event having telescopic handling, jamming sessions, poetry sessions, etcetera.",
    "prizes": "Exciting Prize Pool of 10K!",
    "timeline": "20:00 PM Onwards on 27th January 2023 and 28th January 2023",
    "payment": 199,
    "contacts":
      [
        {
          "name": "xx",
          "number": "xx",
          "email": "xx",
        },
        {
          "name": "xx",
          "number": "+xx",
          "email": "xx",
        },
        {
          "name": "xx",
          "number": "xx",
          "email": "xx",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/17WKj7_woMQJF4zot30EwvW3Qmw3zfPE4/view?usp=share_link",
    "link": "",
    "clubemail": "astronomyclub@lnmiit.ac.in",
  },
  {
    "id": "6",
    "name": "Catia - Design Contest",
    "club": "Coding and Engineering Design",
    "participation": "Solo Participation",
    "imgName": "./images/events/astronomy/starpix/image.jpg",
    "poster": "/images/events/astronomy/starpix/poster.jpg",
    "about": "Astrophotography bridges the gap between art and science, highlighting the natural beauty of our Universe. The Astronomy club of LNMIIT brings you an online Astrophotography event for all the stargazers and astrophotographers! Get your gear all set to capture the colors within the night sky and submit them to us with a short description.",
    "structure": "Online Astrophotography Event.",
    "prizes": "Prizes Worth 15K!",
    "timeline": "13th January 2023 to 23rd January 2023",
    "payment": 199,
    "contacts":
      [
        {
          "name": "Shubhankar Bhatt",
          "number": "+91 99970 78807",
          "email": "20uec129@lnmiit.ac.in",
        },
        {
          "name": "Manan Mishra",
          "number": "+91 73405 31368",
          "email": "20ucc062@lnmiit.ac.in",
        },
        {
          "name": "Parth Somani",
          "number": "+91 87668 96322",
          "email": "21dcs007@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/17KJjELmwiHi-XS9HrSZ8SQvAc3Q6Qgin/view?usp=share_link",
    "link": "https://unstop.com/creative-cultural-event/starpix-lnm-institute-of-information-technology-lnmiit-jaipur-585843",
    "clubemail": "astronomyclub@lnmiit.ac.in",
  },
  {
    "id": "7",
    "name": "Cicuit Design",
    "club": "Coding and Engineering Design",
    "participation": "Solo Participation",
    "imgName": "./images/events/cybros/c-peak/image.jpg",
    "poster": "/images/events/cybros/c-peak/poster.jpg",
    "about": "C-PEAK is an elimination tournament. Each round will be a normal one-person competitive programming contest in which the bottom half of the standing will be eliminated and the top half will qualify for the next round.",
    "structure": "",
    "prizes": "Top rankers will get Exciting goodies",
    "timeline": "27-28 January 2023",
    "payment": 199,
    "contacts":
      [
        {
          "name": "Astha Singh",
          "number": "+91 63765 79645",
          "email": "20ucs040@lnmiit.ac.in",
        },
        {
          "name": "Shivral Somani",
          "number": "+91 63768 22085",
          "email": "20ucs184@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://docs.google.com/document/d/1Z_0ZrqXATSKFc239i15f7O4zVW-Iy1uS/edit?usp=sharing&ouid=103682676179344015200&rtpof=true&sd=true",
    "link": "",
    "clubemail": "cybrosclub@lnmiit.ac.in",
  },
  {
    "id": "8",
    "name": "ML Mania",
    "club": "Coding and Engineering Design",
    "participation": "Solo Participation",
    "imgName": "./images/events/cybros/cpduels/image.jpg",
    "poster": "/images/events/cybros/cpduels/poster.jpg",
    "about": "CP DUEL is an in-person 1v1 knockout tournament. As the meaning of “duel” suggests this will be a “coding combat” between 2 individuals i.e both the participants will be given the same problem and the first person to solve it wins.",
    "structure": "1V1 with fast thinking",
    "prizes": "Top rankers will get Exciting goodies",
    "timeline": "27-28 January 2023",
    "payment": 199,
    "contacts":
      [
        {
          "name": "Astha Singh",
          "number": "+91 63765 79645",
          "email": "20ucs040@lnmiit.ac.in",
        },
        {
          "name": "Shivral Somani",
          "number": "+91 63768 22085",
          "email": "20ucs184@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://docs.google.com/document/d/1Z_0ZrqXATSKFc239i15f7O4zVW-Iy1uS/edit?usp=sharing&ouid=103682676179344015200&rtpof=true&sd=true",
    "link": "",
    "clubemail": "cybrosclub@lnmiit.ac.in",
  },
  {
    "id": "9",
    "name": "ENIGMA",
    "club": "Quiz and Mathematical Aptitude",
    "participation": "Solo Participation",
    "imgName": "./images/events/cybros/enigma/image.jpg",
    "poster": "/images/events/cybros/enigma/poster.jpg",
    "about": "This is Cybros’ flagship rated contest. It is a normal one-person competitive programming contest. This is an onsite round in addition to the official rated round in Codeforces.",
    "structure": "Onsite competitive programming contest",
    "prizes": "Prizes Worth 30K",
    "timeline": "19 December 2022 - Online round concluded 29 January 2023 - Onsite Round",
    "payment": 199,
    "contacts":
      [
        {
          "name": "Astha Singh",
          "number": "+91 63765 79645",
          "email": "20ucs040@lnmiit.ac.in",
        },
        {
          "name": "Shivral Somani",
          "number": "+91 63768 22085",
          "email": "20ucs184@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://docs.google.com/document/d/1Z_0ZrqXATSKFc239i15f7O4zVW-Iy1uS/edit?usp=sharing&ouid=103682676179344015200&rtpof=true&sd=true",
    "link": "",
    "clubemail": "cybrosclub@lnmiit.ac.in",
  },
  {
    "id": "10",
    "name": "Math Mania",
    "club": "Quiz and Mathematical Aptitude",
    "participation": "Team Participation",
    "imgName": "./images/events/cybros/iupc/image.jpg",
    "poster": "/images/events/cybros/iupc/poster.jpg",
    "structure": "ICPC Structure with Team Size of Max 3 Members",
    "prizes": "Prizes Worth 50K",
    "timeline": "28th January 2023",
    "payment": 199,
    "contacts":
      [
        {
          "name": "Astha Singh",
          "number": "+91 63765 79645",
          "email": "20ucs040@lnmiit.ac.in",
        },
        {
          "name": "Shivral Somani",
          "number": "+91 63768 22085",
          "email": "20ucs184@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://docs.google.com/document/d/1Z_0ZrqXATSKFc239i15f7O4zVW-Iy1uS/edit?usp=sharing&ouid=103682676179344015200&rtpof=true&sd=true",
    "link": "",
    "clubemail": "cybrosclub@lnmiit.ac.in",
  },
  {
    "id": "11",
    "name": "NFS - Most Wanted",
    "club": "Gaming",
    "participation": "Solo/Team Participation",
    "imgName": "./images/events/debsoc/changemymind/image.jpg",
    "poster": "/images/events/debsoc/changemymind/poster.jpg",
    "about": "\"Change My Mind\" event is a public discussion forum where individuals will be presented with a random opinion to which you’ll have to convince the chair with argumentation to adhere to your own thoughts on the topic.",
    "structure": "On site passively-aggressive refutal",
    "prizes": "The winners will be awarded prizes, goodies and vouchers worth Rs. 6000/-.",
    "timeline": "27th, 28th and 29th January 2023",
    "payment": 199,
    "contacts":
      [
        {
          "name": "Arjun Saxena",
          "number": "+91 95714 85158",
          "email": "20ucc021@lnmiit.ac.in",
        },
        {
          "name": "Divyanshi Gautam",
          "number": "+91 94624 21299",
          "email": "20ucs066@lnmiit.ac.in",
        },
        {
          "name": "Saumya Kalra",
          "number": "+91 6375 548121",
          "email": "20uec119@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1nZtXPLpR5vT78HMNWDVkrw1_HyV-N33E/view?usp=share_link",
    "link": "",
    "clubemail": "debsoc@lnmiit.ac.in",
  },
  {
    "id": "12",
    "name": "Fifa",
    "club": "Gaming",
    "participation": "Solo Participation",
    "imgName": "./images/events/debsoc/plinth_mun23/image.jpg",
    "poster": "/images/events/debsoc/plinth_mun23/poster.jpg",
    "about": "At a MUN conference, delegates(students) will each represent a nation/organization to solve world problems working with other delegates. The event will be 2 days long and will have UNGA, AIPPM and UNSC as the committees.",
    "structure": "Model United Nations Organisation Conference",
    "prizes": "PMUN'23 has got a massive prize pool of Rs. 92,000/-",
    "timeline": "Application deadline: 21st Jaunary 2023     Conference dates: 27th January 2023 and 28th January 2023",
    "payment": 1200,
    "contacts":
      [
        {
          "name": "Arjun Saxena",
          "number": "+91 95714 85158",
          "email": "20ucc021@lnmiit.ac.in",
        },
        {
          "name": "Divyanshi Gautam",
          "number": "+91 94624 21299",
          "email": "20ucs066@lnmiit.ac.in",
        },
        {
          "name": "Saumya Kalra",
          "number": "+91 6375 548121",
          "email": "20uec119@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1lAu1T0sBEtbuDqSYWd-WFSkoa447bBWc/view?usp=share_link",
    "link": "",
    "clubemail": "debsoc@lnmiit.ac.in",
  },
  {
    "id": "13",
    "name": "Robo Fifa",
    "club": "Robotics",
    "participation": "Solo Participation",
    "imgName": "./images/events/debsoc/graffitiwall/image.jpg",
    "poster": "/images/events/debsoc/graffitiwall/poster.jpg",
    "about": "Graffiti wall will give an opportunity to the viewers to actually put their thoughts via a sheet of paper or drawings on a blank canvas.",
    "structure": "On site idea centric graffiti",
    "prizes": "",
    "timeline": "27th, 28th and 29th January 2023",
    "payment": 199,
    "contacts":
      [
        {
          "name": "Arjun Saxena",
          "number": "+91 95714 85158",
          "email": "20ucc021@lnmiit.ac.in",
        },
        {
          "name": "Divyanshi Gautam",
          "number": "+91 94624 21299",
          "email": "20ucs066@lnmiit.ac.in",
        },
        {
          "name": "Saumya Kalra",
          "number": "+91 6375 548121",
          "email": "20uec119@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1HCrqnCy_ya334RfaJEY5XRWwZ2VC5mpk/view?usp=share_link",
    "link": "",
    "clubemail": "debsoc@lnmiit.ac.in",
  },
  {
    "id": "14",
    "name": "Robo War",
    "club": "Robotics",
    "participation": "Team Participation",
    "imgName": "./images/events/e-cell/sharktank/image.jpg",
    "poster": "/images/events/e-cell/sharktank/poster.jpg",
    "about": "A four-round competition that leads to the final stage of negotiations with the 'investor' in exchange for 'equity'. Scale-up your startup by earning mentorship and guidance by renowned Entrepreneurs from across the nation and established Angel Investors in this ecosystem.",
    "structure": "Round 1 (Online): Your startup's Pitch Deck needs to be Submitted on Unstop Platform ; Round 2 (Online): A video pitch describing your startup in the most creative form needs to be Submitted on Unstop Platform ; Round 3 (Offline): Offline Pitching in front of Judges (established Entrepreneurs); Round 4 (Offline): Final pitch in front of Angel Investors and Micro Venture Capitalists.",
    "prizes": "Cash Prizes worth a minimum of Rs. 50,000/- will be given to the winners including Prototype Funding of Rs.35,000+",
    "timeline": "Round 1 (Online): 14 December 2022 - 12 January 2023; Round 2 (Online): 13 Januray - 20 January 2023; Round 3 (Offline): 27th January 2023; Round 4 (Offline): 28th January 2023",
    "payment": 700,
    "contacts":
      [
        {
          "name": "Vaishvi Bansal",
          "number": "+91 80007 68730",
          "email": "20uec143@lnmiit.ac.in",
        },
        {
          "name": "Sarthak Kapoor",
          "number": "+91 63948 10829",
          "email": "20uec115@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1a2gUgb00k4zdFcPKsalunUtqlmIBGa3j/view?usp=share_link",
    "link": "",
    "clubemail": "ecell@lnmiit.ac.in",
  },
  {
    "id": "15",
    "name": "Chase the Maze",
    "club": "Robotics",
    "participation": "Solo Participation",
    "imgName": "./images/events/e-cell/virtualstocksim/image.jpg",
    "poster": "/images/events/e-cell/virtualstocksim/poster.jpg",
    "about": "An online mode event where all the students will be provided a minimum virtual cash amount of 10 lakh Rupees and they will have the authoriy to use that amount and invest it in stocks and learn about the trading experience at the best possible way.",
    "structure": "The event would be happening on designated Stock Simulation Platform and the prize distribution ceremony would take place during Plinth ",
    "prizes": "Cash Prizes worth a minimum of Rs. 10,000/- will be given to the winners.",
    "timeline": "21 January 2023 - Registrations Closes, 23 January 2023 to 27 January 2023 - Contest dates",
    "payment": 199,
    "contacts":
      [
        {
          "name": "Vaishvi Bansal",
          "number": "+91 80007 68730",
          "email": "20uec143@lnmiit.ac.in",
        },
        {
          "name": "Sarthak Kapoor",
          "number": "+91 63948 10829",
          "email": "20uec115@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1e6hYeltcu_kCMUJAsYvJSFs8hfhpnCya/view?usp=share_link",
    "link": "",
    "clubemail": "ecell@lnmiit.ac.in",
  },
  {
    "id": "25",
    "name": "Line Follower",
    "club": "Robotics",
    "club2": "LCRAI",
    "participation": "Team Participation",
    "imgName": "./images/events/phoenix/robowars/image.jpg",
    "poster": "/images/events/phoenix/robowars/poster.png",
    "about": "A Competition in which robot battles using various methods to incapacitate the opponents robots.",
    "structure": "Points will be given by judges based on aggression, damage, and control. A team may win by knockout if it successfully immobilizes its opponent for 10 seconds. In case of a double KO, the winner will be decided by points.",
    "prizes": "1st Prize - ₹40000, 2nd Prize - ₹20000, Prizes worth ₹200000 ",
    "timeline": "27 JAN (2PM-5PM) & 29 JAN (3PM-6PM)",
    "payment": 1000,
    "contacts":
      [
        {
          "name": "Ayush sharma",
          "number": "+91 94602 57928",
          "email": "20ucc123@lnmiit.ac.in",
        },
        {
          "name": "Nanik Chaturvedi",
          "number": "+91 82093 93282",
          "email": "21ucc068@lnmiit.ac.in",
        },
        {
          "name": "Paras Jain",
          "number": "+91 75978 61350",
          "email": "21uec157@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1my1PwBubvkmib2Q3mzOiosMj8UD1DCxX/view?usp=share_link",
    "link": "",
    "clubemail": "phoenixclub@lnmiit.ac.in",
  },
  

];
