import { Fragment } from "react";
import React from "react";
export const teams = [
  {
    team: "Tech Team",
    leads: [
      {
        name: "Abhishek Mishra",
        image: "./images/teams/gunitY19.jfif",
        designation: "Developer",
        phone: "CSE-4th Year",
        mail: "b.s.abhi152@gmail.com",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Nishka Shrimali",
        image: "./images/teams/Nishka.jpg",
        designation: "Developer",
        phone:"CSE-3rd Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Ramjee Rai",
        image: "./images/teams/raja.jpg",
        designation: "Developer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Sayantan Paul",
        image: "./images/teams/raja.jpg",
        designation: "Developer",
        phone: "IT-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Tanisha Gupta",
        image: "./images/teams/raja.jpg",
        designation: "Developer",
        phone: "IT-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
    ],
    members: [],
  },
  {
    team: "Event Organizers",
    leads: [
      {
        name: "Abhishek Mishra",
        image: "./images/teams/sharma.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Ramjee Rai",
        image: "./images/teams/sharma.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Abhishek Mishra",
        image: "./images/teams/sharma.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Abhishek Mishra",
        image: "./images/teams/sharma.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Abhishek Mishra",
        image: "./images/teams/sharma.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Abhishek Mishra",
        image: "./images/teams/sharma.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Abhishek Mishra",
        image: "./images/teams/sharma.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Abhishek Mishra",
        image: "./images/teams/sharma.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      
    ],
    members: [],
  },
  
];