
export const teams = [
  {
    team: "Tech Team",
    leads: [
      {
        name: "Abhishek Mishra",
        image: "./images/teams/Abhishek Mishra.jpg",
        designation: "Developer",
        phone: "CSE-4th Year",
        mail: "b.s.abhi152@gmail.com",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Nishka Shrimali",
        image: "./images/teams/Nishka.jpg",
        designation: "Developer",
        phone:"CSE-3rd Year",
        mail: "mailto:shrimalinishka@gmail.com",
        facebook: "/",
        instagram: "/",
        linkedin: "https://www.linkedin.com/in/nishka-shrimali-83419a225/",
      },
      {
        name: "Ramjee Rai",
        image: "./images/teams/Ramjee Rai.JPG",
        designation: "Developer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Sayantan Paul",
        image: "./images/teams/Sayantan Paul.jpeg",
        designation: "Developer",
        phone: "IT-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Tanisha Gupta",
        image: "./images/teams/Tanisha Gupta.jpg",
        designation: "Developer",
        phone: "IT-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
    ],
    members: [],
  },
  {
    team: "Event Organizers",
    leads: [
      {
        name: "Abhishek Mishra",
        image: "./images/teams/Abhishek Mishra.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Manas Kumar Manna",
        image: "./images/teams/Manas Kumar Manna.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Srijit Sarkar",
        image: "./images/teams/Srijit Sarkar.jpg",
        designation: "Organizer",
        phone: "IT-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Jayant Joshi",
        image: "./images/teams/Jayant Joshi.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Suchi Kumari",
        image: "./images/teams/Suchi Kumari.jpeg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Sneha Singh",
        image: "./images/teams/Sneha Singh.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Tanisha Gupta",
        image: "./images/teams/Tanisha Gupta.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Atreyee Kar",
        image: "./images/teams/Atreyee Kar.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Deblina Banerjee ",
        image: "./images/teams/Deblina Banerjee.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Sayantan Paul",
        image: "./images/teams/Sayantan Paul.jpeg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Priyodeep Mukherjee ",
        image: "./images/teams/Priyodeep Mukherjee.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Swapnanil Saha",
        image: "./images/teams/Swapnanil Saha.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Anushka Kar",
        image: "./images/teams/Anushka Kar.png",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Sohini Dutta",
        image: "./images/teams/Sohini Dutta.jpeg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Arka Pravo Dutta",
        image: "./images/teams/Arka Pravo Dutta.png",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Archisman Mangal",
        image: "./images/teams/Archisman Mangal.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Suranjana Saha",
        image: "./images/teams/Suranjana Saha.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Rohan Saha",
        image: "./images/teams/Rohan Saha.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Swapnodeep Banerjee",
        image: "./images/teams/Swapnodeep Banerjee.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Ramjee Rai",
        image: "./images/teams/Ramjee Rai.JPG",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      
      
    ],
    members: [],
  },
  
];