
export const teams = [
  {
    team: "Tech Team",
    leads: [
      {
        name: "Abhishek Mishra",
        image: "./images/teams/Abhishek Mishra.jpg",
        designation: "Developer",
        phone: "CSE-4th Year",
        mail: "mailto:b.s.abhi152@gmail.com",
        instagram: "https://wa.me/+918887850034",
        linkedin: "/",
      },
      {
        name: "Nishka Shrimali",
        image: "./images/teams/Nishka.jpg",
        designation: "Developer",
        phone:"CSE-3rd Year",
        mail: "mailto:shrimalinishka@gmail.com",
        facebook: "/",
        instagram: " https://wa.me/+916291764011",
        linkedin: "https://www.linkedin.com/in/nishka-shrimali-83419a225/",
      },
      {
        name: "Ramjee Rai",
        image: "./images/teams/Ramjee Rai.JPG",
        designation: "Developer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "https://wa.me/+918777281405",
        linkedin: "/",
      },
      {
        name: "Sayantan Paul",
        image: "./images/teams/Sayantan Paul.jpeg",
        designation: "Developer",
        phone: "IT-4th Year",
        mail: "/",
        instagram: "https://wa.me/+916291413882",
        linkedin: "/",
      },
      {
        name: "Tanisha Gupta",
        image: "./images/teams/Tanisha Gupta.jpg",
        designation: "Developer",
        phone: "IT-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "https://wa.me/+918420550887",
        linkedin: "/",
      },
    ],
    members: [],
  },
  {
    team: "Event Organizers",
    leads: [
      {
        name: "Abhishek Mishra",
        image: "./images/teams/Abhishek Mishra.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "https://wa.me/+918887850034",
        linkedin: "/",
      },
      {
        name: "Manas Kumar Manna",
        image: "./images/teams/Manas Kumar Manna.jpg",
        designation: "Organizer",
        phone: "CSE-DS-4th Year",
        mail: "mailto:manas2018manna@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+917362970829",
        linkedin: "https://www.linkedin.com/in/manas-kumar-manna-116561228",
      },
      {
        name: "Srijit Sarkar",
        image: "./images/teams/Srijit Sarkar.jpg",
        designation: "Organizer",
        phone: "IT-4th Year",
        mail: "mailto:srijitsarkar17@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+919432902403",
        linkedin: "/",
      },
      {
        name: "Jayant Joshi",
        image: "./images/teams/Jayant Joshi.jpg",
        designation: "Organizer",
        phone: "AUE-4th Year",
        mail: "mailto:jayant.joshi01@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+917059633144",
        linkedin: "https://in.linkedin.com/in/jayant-joshi-6b396523b",
      },
      {
        name: "Suchi Kumari",
        image: "./images/teams/Suchi Kumari.jpeg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "mailto:kumarisuchi569@gmail.com ",
        facebook: "/",
        instagram: "https://wa.me/+916200254450",
        linkedin: "https://www.linkedin.com/in/suchi-kumari-727741224/",
      },
      {
        name: "Sneha Singh",
        image: "./images/teams/Sneha Singh.jpg",
        designation: "Organizer",
        phone: "CSE-DS-4th Year",
        mail: "mailto:snehasinggh65@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+919007923300",
        linkedin: "https://www.linkedin.com/in/sneha-singh-ab2528215",
      },
      {
        name: "Tanisha Gupta",
        image: "./images/teams/Tanisha Gupta.jpg",
        designation: "Organizer",
        phone: "IT-4th Year",
        mail: "mailto:tanishagupta1234.college@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+918420550887",
        linkedin: "https://www.linkedin.com/in/tanisha-gupta-a81158210",
      },
      {
        name: "Atreyee Kar",
        image: "./images/teams/Atreyee Kar.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "mailto:karatreyee2002@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+918777721356",
        linkedin: "https://www.linkedin.com/in/atreyee-kar-6535b5215",
      },
      {
        name: "Deblina Banerjee ",
        image: "./images/teams/Deblina Banerjee.jpg",
        designation: "Organizer",
        phone: "IT-4th Year",
        mail: "mailto:deblinabanerjee780@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+91964192469",
        linkedin: "https://www.linkedin.com/in/deblina-banerjee-231290206?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        name: "Sayantan Paul",
        image: "./images/teams/Sayantan Paul.jpeg",
        designation: "Organizer",
        phone: "IT-4th Year",
        mail: "mailto:sayantan.college6291@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+916291413882",
        linkedin: "https://www.linkedin.com/in/imsayantanpaul",
      },
      {
        name: "Priyodeep Mukherjee ",
        image: "./images/teams/Priyodeep Mukherjee.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "mailto:priyodeep.mukherjee02@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+918981534701",
        linkedin: "https://www.linkedin.com/in/priyodeep-mukherjee-062783216?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        name: "Swapnanil Saha",
        image: "./images/teams/Swapnanil Saha.jpg",
        designation: "Organizer",
        phone: "ECE-4th Year",
        mail: "/mailto:nilswapnasaha@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+916291326445",
        linkedin: "www.linkedin.com/in/swapnanil-saha-1a5675246",
      },
      {
        name: "Anushka Kar",
        image: "./images/teams/Anushka Kar.png",
        designation: "Organizer",
        phone: "IT-4th Year",
        mail: "mailto:anushka.kar123@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+91874702562",
        linkedin: "/",
      },
      {
        name: "Sohini Dutta",
        image: "./images/teams/Sohini Dutta.jpeg",
        designation: "Organizer",
        phone: "ECE-4th Year",
        mail: "mailto:sohinidutta65@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+919831150237",
        linkedin: "/",
      },
      {
        name: "Arka Pravo Dutta",
        image: "./images/teams/Arka Pravo Dutta.png",
        designation: "Organizer",
        phone: "CSE-DS-4th Year",
        mail: "mailto:dutta.arkapravo11@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+917439125500",
        linkedin: "https://www.linkedin.com/in/arka-pravo-dutta-359200215?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        name: "Archisman Mangal",
        image: "./images/teams/Archisman Mangal.jpg",
        designation: "Organizer",
        phone: "EE-4th Year",
        mail: "mailto:archismanmangal2002@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+919163980262",
        linkedin: "/",
      },
      {
        name: "Suranjana Saha",
        image: "./images/teams/Suranjana Saha.jpg",
        designation: "Organizer",
        phone: "CSE-DS-4th Year",
        mail: "mailto:suranjanasaha37@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+917362970829",
        linkedin: "https://in.linkedin.com/in/suranjana-saha-1b2529215",
      },
      {
        name: "Rohan Saha",
        image: "./images/teams/Rohan Saha.jpg",
        designation: "Organizer",
        phone: "EE-4th Year",
        mail: "mailto:rohansaha2001@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+918647862863",
        linkedin: "www.linkedin.com/in/rohan-saha-6b9448223",
      },
      {
        name: "Swapnodeep Banerjee",
        image: "./images/teams/Swapnodeep Banerjee.jpg",
        designation: "Organizer",
        phone: "EE-4th Year",
        mail: "mailto:banerjee.swapnodeep10@gmail.com ",
        facebook: "/",
        instagram: "https://wa.me/+919903143255",
        linkedin: "linkedin.com/in/swapnodeepbanerjee",
      },
      {
        name: "Ramjee Rai",
        image: "./images/teams/Ramjee Rai.JPG",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "mailto:rairamjee2@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+918777281405",
        linkedin: "https://www.linkedin.com/in/ramjee-rai-a3a49a244",
      },
      {
        name: "Aritra Dalui",
        image: "./images/teams/Aritra Dalui.JPG",
        designation: "Organizer",
        phone: "EE-4th Year",
        mail: "mailto:aritradalui2002@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+917439135764",
        linkedin: "linkedin.com/in/aritra-dalui",
      },
      {
        name: "Kabita Sahu",
        image: "./images/teams/Kabita Sahu.jpg",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "mailto:kabitasahu434@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+918902737027",
        linkedin: "/",
      },
      {
        name: "Navanil Ghosh",
        image: "./images/teams/Navanil Ghosh.jpg",
        designation: "Organizer",
        phone: "CSE-DS-4th Year",
        mail: "mailto:navanil2001@gmail.com",
        facebook: "/",
        instagram: "https://wa.me/+919123792013",
        linkedin: "www.linkedin.com/in/navanil-ghosh-11ab43217",
      },
      {
        name: "Kingshuk Sarkar ",
        image: "./images/teams/cartoon.webp",
        designation: "Organizer",
        phone: "ME-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "https://wa.me/+919547852966",
        linkedin: "/",
      },
      {
        name: "Lokesh Nahar",
        image: "./images/teams/cartoon.webp",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "https://wa.me/+919910138904",
        linkedin: "/",
      },
      {
        name: "Bithika Das ",
        image: "./images/teams/cartoon.webp",
        designation: "Organizer",
        phone: "AUE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "https://wa.me/+917980009670",
        linkedin: "/",
      },
      {
        name: "Binit Kumar Sha",
        image: "./images/teams/cartoon.webp",
        designation: "Organizer",
        phone: "AUE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "https://wa.me/+919903296261",
        linkedin: "/",
      },
      {
        name: "Jagaran Biswas",
        image: "./images/teams/cartoon.webp",
        designation: "Organizer",
        phone: "AUE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "https://wa.me/+918926707701",
        linkedin: "/",
      },
      {
        name: "Abhijit Mukherjee",
        image: "./images/teams/cartoon.webp",
        designation: "Organizer",
        phone: "ME-4th Year",
        mail: "/",
 
        instagram: "https://wa.me/+916291513319",
        linkedin: "/",
      },
      {
        name: "Suman Das",
        image: "./images/teams/cartoon.webp",
        designation: "Organizer",
        phone: "ME-4th Year",
        mail: "/",
   
        instagram: "https://wa.me/+919051672668",
        linkedin: "/",
      },
      {
        name: "Subhojit Majumdar ",
        image: "./images/teams/cartoon.webp",
        designation: "Organizer",
        phone: "ME-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "https://wa.me/+918697154474",
        linkedin: "/",
      },
      {
        name: "Anirban Ghosh",
        image: "./images/teams/cartoon.webp",
        designation: "Organizer",
        phone: "CSE-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "https://wa.me/+919477465454",
        linkedin: "/",
      },
      {
        name: "Arnab Bardhan",
        image: "./images/teams/cartoon.webp",
        designation: "Organizer",
        phone: "ME-4th Year",
        mail: "/",
        facebook: "/",
        instagram: "https://wa.me/+917890743642",
        linkedin: "/",
      },
    ],
    members: [],
  },
  
];